# Project: 9~12°à36
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o io.o schedule.o
LINKOBJ  = main.o io.o schedule.o
LIBS     = -L"D:/Environment/Dev-Cpp/MinGW64/lib" -L"D:/Environment/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Environment/Dev-Cpp/MinGW64/include" -I"D:/Environment/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Environment/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Environment/Dev-Cpp/MinGW64/include" -I"D:/Environment/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Environment/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Environment/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 9~12°à36.exe
CXXFLAGS = $(CXXINCS) -std=c11
CFLAGS   = $(INCS) -std=c11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

io.o: io.c
	$(CC) -c io.c -o io.o $(CFLAGS)

schedule.o: schedule.c
	$(CC) -c schedule.c -o schedule.o $(CFLAGS)
